//
// Created by Alex on 12/6/2021.
//

#ifndef SFML_PROJECT_IMAGENAME_H
#define SFML_PROJECT_IMAGENAME_H
enum ImageName
{
    MENU, WINNER, GAMESCREEN, BACK, ACES, TWOS, THREES, FOURS, FIVES, SIXS, SEVENS, EIGHTS, NINES, TENS, JACKS, QUEENS, KINGS,


    LASTIMAGE
};
#endif //SFML_PROJECT_IMAGENAME_H
