//
// Created by Alex on 10/25/2021.
//

#ifndef SFML_PROJECT_RANKSENUM_H
#define SFML_PROJECT_RANKSENUM_H

enum RanksENUM{
    ACE = 1, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING
};
#endif //SFML_PROJECT_RANKSENUM_H
